DROP TABLE IF EXISTS T_USER;
	
CREATE TABLE T_USER (
	ID INT,
	NAME VARCHAR(100),
	AGE	INT,
	SEX CHAR(2),
	REGISTERDATE TIMESTAMP,
	CREATEDATE	TIMESTAMP,
	UPDATEDATE	TIMESTAMP,
	USERSTATE	INT
);

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (ID);

DROP TABLE IF EXISTS T_ORDER;

CREATE TABLE T_ORDER(
	ID INT,
	CREATEDATE TIMESTAMP,
	UPDATEDATE	TIMESTAMP,
	STATE	VARCHAR(10),
	UID	INT

);

ALTER TABLE T_ORDER ADD CONSTRAINT PK_T_ORDER PRIMARY KEY (ID);

