DECLARE
	N NUMBER;
	BEGIN
		SELECT COUNT(*) INTO N FROM ALL_TABLES WHERE TABLE_NAME='T_USER';
		IF (N=1) THEN
		EXECUTE IMMEDIATE 'DROP TABLE T_USER CASCADE CONSTRAINT';
		END IF;
	END;
	/
	
CREATE TABLE T_USER (
	ID INT,
	NAME VARCHAR(100),
	AGE	INT,
	SEX CHAR(2),
	REGISTERDATE TIMESTAMP,
	CREATEDATE	TIMESTAMP,
	UPDATEDATE	TIMESTAMP,
	USERSTATE	INT
);

ALTER TABLE T_USER ADD CONSTRAINT PK_T_USER PRIMARY KEY (ID);

DECLARE
	N NUMBER;
	BEGIN
		SELECT COUNT(*) INTO N FROM ALL_TABLES WHERE TABLE_NAME='T_ORDER';
		IF (N=1) THEN
		EXECUTE IMMEDIATE 'DROP TABLE T_ORDER CASCADE CONSTRAINT';
		END IF;
	END;
	/
	
CREATE TABLE T_ORDER(
	ID INT,
	CREATEDATE TIMESTAMP,
	UPDATEDATE	TIMESTAMP,
	STATE	VARCHAR(10),
	UID	INT

);

ALTER TABLE T_ORDER ADD CONSTRAINT PK_T_ORDER PRIMARY KEY (ID);



